version: "3.4"

services:
  db:
    image: 3dcitydb/3dcitydb-pg:13-3.1-4.1.0
#    env_file: .env
    shm_size: 1g
    restart: unless-stopped
    ports:
      - "6543:5432"
    environment:
      - POSTGRES_DB=citydb
      - POSTGRES_USER=citydb
      #      - POSTGIS_SFCGAL=<true|false|yes|no>
      - POSTGRES_PASSWORD=citydb       
      - SRID=4839 
      - HEIGHT_EPSG=4839
#      - GMLSRSNAME=<mySrsName> 
    volumes:
      - data-pgsql:/var/lib/postgresql/data

  ontop:
    image: ontop/ontop-endpoint:4.1.0
#    env_file: .env
    restart: unless-stopped
    environment:
      ONTOP_ONTOLOGY_FILE: /opt/ontop/input/citygml2.0.owl
      ONTOP_XML_CATALOG_FILE: /opt/ontop/input/catalog-v001.xml
      ONTOP_MAPPING_FILE: /opt/ontop/input/citygml2.0.obda
      ONTOP_PROPERTIES_FILE: /opt/ontop/input/citygml2.0.docker.properties
#      ONTOP_PORTAL_FILE: /opt/ontop/input/dest.portal.toml
      ONTOP_CORS_ALLOWED_ORIGINS: "*"
      ONTOP_DEV_MODE: "true"
    volumes:
      - ./vkg:/opt/ontop/input
      - ./jdbc:/opt/ontop/jdbc
      - ./wait-for-it:/opt/wait-for-it
    entrypoint:
      [
        "/opt/wait-for-it/wait-for-it.sh",
        "db:5432",
        "--timeout=0",
        "--strict",
        "--",
        "/opt/ontop/entrypoint.sh",
      ]
    ports:
      - "8082:8080"

volumes:
  data-pgsql: { }
    